#!/usr/bin/env bash

DEPLOYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
git archive --format=tar  --prefix=kite-0.1.0/ HEAD | bzip2 > ${DEPLOYDIR}/kite-0.1.0.tar.bz2

DEPLOYTYPE=${DEPLOYTYPE:-vbox}
DEPLOYMENT=${DEPLOYMENT:-flockd-${DEPLOYTYPE}}

if nixops info -d ${DEPLOYMENT}; then
    echo "Deployment already created"
else
    nixops create -d ${DEPLOYMENT} ${DEPLOYDIR}/deploy.nix ${DEPLOYDIR}/deploy-${DEPLOYTYPE}.nix
fi

echo "Building..."
nixops deploy -d ${DEPLOYMENT} --build-only --show-trace

echo "Deploying..."
nixops deploy -d ${DEPLOYMENT}
