// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "StorkdLocal.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::stork::thrift;

class StorkdLocalHandler : virtual public StorkdLocalIf {
 public:
  StorkdLocalHandler() {
    // Your initialization goes here
  }

  void joinSwarm(SwarmId& _return, const std::string& swarmUri) {
    // Your implementation goes here
    printf("joinSwarm\n");
  }

  void leaveSwarm(const SwarmId& swarmId) {
    // Your implementation goes here
    printf("leaveSwarm\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<StorkdLocalHandler> handler(new StorkdLocalHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new StorkdLocalProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

