/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storkd_constants.h"

namespace stork { namespace thrift {

const storkdConstants g_storkd_constants;

storkdConstants::storkdConstants() {
}

}} // namespace

