/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef storkd_CONSTANTS_H
#define storkd_CONSTANTS_H

#include "storkd_types.h"

namespace stork { namespace thrift {

class storkdConstants {
 public:
  storkdConstants();

};

extern const storkdConstants g_storkd_constants;

}} // namespace

#endif
